### ISSUE TITLE
Put Access Key and Secret Key in a dot file

### ISSUE THREAD

**Issue by marcusalmeida** [s3git/s3git#10]
A suggestion. It could be a good idea to put the _Access Key_ and _Secret Key_ in a configuration file, such as a dot file ( eg .s3git.cfg ) . So we would not need to expose this information whenever you execute a command.

**Comment by tzz** [comment]
It would be convenient if `~/.aws/config` and `~/.aws/credentials` could be parsed instead of naming a unique configuration file, so the configuration could be shared with the aws-cli: https://docs.aws.amazon.com/cli/latest/userguide/cli-chap-getting-started.html

```
[default]
aws_access_key_id = x
aws_secret_access_key = y

[profile p1]
aws_access_key_id = a
aws_secret_access_key = b
```

**Comment by marcusalmeida** [comment]
Nice. I had not thought of that possibility. 
The only drawback is that the user has to install the _aws-cli_ to this model. In fact I do not know if that's a problem.

**Comment by fwessels** [comment]
Great suggestion, a --profile option would be handy that maybe first looks for a `~/.s3git/credentials` file and secondly for a `~/.aws/credentials` -- if we stick to the aws format then that should be easy to use.

**Comment by tzz** [comment]
`aws-cli` is not needed. The configuration format and filename are the only things that come from it.

The same format is also used by the boto library (and Ansible), and the `~/aws/{config,credentials}` are the only filenames that are shared between boto and `aws-cli`: https://boto.readthedocs.io/en/latest/boto_config_tut.html

The `--profile` option, if created, should be complemented with an environment variable `AWS_PROFILE` since it's easier to write reusable scripts that way.

**Comment by fwessels** [comment]
Yes, aws-cli is not needed indeed. And the handling by boto is a nice guideline...

If you feel like hacking a little in Go, I'd be happy to take a PR...   😄

**Comment by tzz** [comment]
@fwessels I don't know Go at all but am willing to give it a try, if no one else wants to step up. I do need some guidance, though.

I think an INI parser library would be better than hacking the parser myself. Looking at https://stackoverflow.com/questions/16465705/how-to-handle-configuration-in-go it seems that https://github.com/vharitonsky/iniflags and http://code.google.com/p/gcfg/ could work. There's a full gcfg example at https://stackoverflow.com/a/16478631/4329000

s3git seems to use https://github.com/spf13/cobra but that doesn't have any configuration parsing built-in. Do you have suggestions? Should this be asked of the https://github.com/spf13/cobra maintainers since it's really not specific to s3git, except for the file location and maybe profile handling?

**Comment by fwessels** [comment]
Wow, that would be fantastic !  (and I can say that Go is a lot of fun to work with...)

Yes, s3git uses cobra for the command line handling, there is some sort of a companion package to that for configuration by the same author (https://github.com/spf13/viper) but that seemed a bit overkill at the time (and it does not support INI files -- see https://github.com/spf13/viper#q--a).

So the http://code.google.com/p/gcfg/ package looks to be pretty good up to the job. And let me know if you run into any issues...

**Comment by tzz** [comment]
After investigation, I like viper a lot, and would rather contribute INI files to it (since s3git would then also accept other formats and environment variables automatically). So the task here becomes to use viper... if you agree. It seems pretty simple from their docs. And I'll try to submit a PR to viper for INI files, but even without it, s3git can start supporting environment variables and JSON and YAML.

**Comment by fwessels** [comment]
No problem with that, but in case the viper project would not accept (a PR for) INI files we wouldn't be able to parse the `~/.aws/credentials` file, right?
However, re-reading the Q&A, they state that they will happily merge INI support, so if that is the case then this is a nice way to go.

**Comment by tzz** [comment]
My currently not 100% working attempt is at https://github.com/s3git/s3git/pull/12

Once that's merged, I can try to implement INI support for Viper.

**Comment by tzz** [comment]
Now that #12 is resolved, you can do

```console
% echo '{ "access": "foobar", "secret": "mypassword" }' > ~/.s3git/config.json
% chmod 600 ~/.s3git/config.json
```

The INI support for `~/.aws/credentials` will come later. I'm not sure if this issue can be closed or not.

**Comment by fwessels** [comment]
Nice, closing this issue (will create seperate issue for INI file support)
